// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netbeam.proto

package netbeam

import (
	context "context"
	fmt "fmt"
	pond "github.com/esnet/proto/go/pond"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Tstamp               *pond.Timestamp `protobuf:"bytes,2,opt,name=tstamp,proto3" json:"tstamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetTstamp() *pond.Timestamp {
	if m != nil {
		return m.Tstamp
	}
	return nil
}

// The namespace, which is made up of the organization and the collection e.g. { organization: "esnet", collection: "prod"}
type Namespace struct {
	// The organization this request is associated with e.g. "esnet"
	Organization string `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	// The collection within the organization's data the request is for. e.g. "prod"
	Collection           string   `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{2}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Namespace) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

// The full resource path e.g. ["devices", "chic-cr5", "interfaces", "1/1/1"]
type Resource struct {
	Path                 []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{3}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type TileRequest struct {
	// The namespace
	Namespace *Namespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The resource as a path
	Resource *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// The metric to get the tile from, for example "traffic/in"
	Metric string `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	// The tile index, for example "1d-1234"
	Index                string   `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileRequest) Reset()         { *m = TileRequest{} }
func (m *TileRequest) String() string { return proto.CompactTextString(m) }
func (*TileRequest) ProtoMessage()    {}
func (*TileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{4}
}

func (m *TileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileRequest.Unmarshal(m, b)
}
func (m *TileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileRequest.Marshal(b, m, deterministic)
}
func (m *TileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileRequest.Merge(m, src)
}
func (m *TileRequest) XXX_Size() int {
	return xxx_messageInfo_TileRequest.Size(m)
}
func (m *TileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TileRequest proto.InternalMessageInfo

func (m *TileRequest) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *TileRequest) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *TileRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *TileRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type Organization struct {
	// The database ID of the organization
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The short name of the organization
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// A longer more descriptive name for the organization
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Creation time
	Created              string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{5}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Organization) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type OrganizationListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrganizationListRequest) Reset()         { *m = OrganizationListRequest{} }
func (m *OrganizationListRequest) String() string { return proto.CompactTextString(m) }
func (*OrganizationListRequest) ProtoMessage()    {}
func (*OrganizationListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{6}
}

func (m *OrganizationListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationListRequest.Unmarshal(m, b)
}
func (m *OrganizationListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationListRequest.Marshal(b, m, deterministic)
}
func (m *OrganizationListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationListRequest.Merge(m, src)
}
func (m *OrganizationListRequest) XXX_Size() int {
	return xxx_messageInfo_OrganizationListRequest.Size(m)
}
func (m *OrganizationListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationListRequest proto.InternalMessageInfo

type OrganizationList struct {
	// The list of organizations
	Organizations        []*Organization `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OrganizationList) Reset()         { *m = OrganizationList{} }
func (m *OrganizationList) String() string { return proto.CompactTextString(m) }
func (*OrganizationList) ProtoMessage()    {}
func (*OrganizationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{7}
}

func (m *OrganizationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationList.Unmarshal(m, b)
}
func (m *OrganizationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationList.Marshal(b, m, deterministic)
}
func (m *OrganizationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationList.Merge(m, src)
}
func (m *OrganizationList) XXX_Size() int {
	return xxx_messageInfo_OrganizationList.Size(m)
}
func (m *OrganizationList) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationList.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationList proto.InternalMessageInfo

func (m *OrganizationList) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type OrganizationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrganizationRequest) Reset()         { *m = OrganizationRequest{} }
func (m *OrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*OrganizationRequest) ProtoMessage()    {}
func (*OrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d69b4fdff410ff, []int{8}
}

func (m *OrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationRequest.Unmarshal(m, b)
}
func (m *OrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationRequest.Marshal(b, m, deterministic)
}
func (m *OrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationRequest.Merge(m, src)
}
func (m *OrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_OrganizationRequest.Size(m)
}
func (m *OrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationRequest proto.InternalMessageInfo

func (m *OrganizationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "netbeam.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "netbeam.HelloReply")
	proto.RegisterType((*Namespace)(nil), "netbeam.Namespace")
	proto.RegisterType((*Resource)(nil), "netbeam.Resource")
	proto.RegisterType((*TileRequest)(nil), "netbeam.TileRequest")
	proto.RegisterType((*Organization)(nil), "netbeam.Organization")
	proto.RegisterType((*OrganizationListRequest)(nil), "netbeam.OrganizationListRequest")
	proto.RegisterType((*OrganizationList)(nil), "netbeam.OrganizationList")
	proto.RegisterType((*OrganizationRequest)(nil), "netbeam.OrganizationRequest")
}

func init() { proto.RegisterFile("netbeam.proto", fileDescriptor_38d69b4fdff410ff) }

var fileDescriptor_38d69b4fdff410ff = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0x92, 0x8f, 0x71, 0x4a, 0xdb, 0x69, 0x01, 0x37, 0x42, 0x95, 0x59, 0x0e, 0x94,
	0x03, 0x09, 0x0a, 0x42, 0x42, 0xe2, 0xc6, 0x01, 0x7a, 0x40, 0x8d, 0xe4, 0xf6, 0xc4, 0x6d, 0x63,
	0x8f, 0x92, 0x95, 0x6c, 0xaf, 0xf1, 0x6e, 0x24, 0xc2, 0x2f, 0xe1, 0xc0, 0x8f, 0xad, 0xbc, 0x59,
	0x3b, 0x9b, 0x2a, 0xbd, 0x79, 0xde, 0xbe, 0xdd, 0x37, 0xef, 0xcd, 0x18, 0x8e, 0x0b, 0xd2, 0x0b,
	0xe2, 0xf9, 0xa4, 0xac, 0xa4, 0x96, 0xd8, 0xb7, 0xe5, 0x18, 0x4a, 0x59, 0xa4, 0x5b, 0x90, 0x31,
	0x18, 0xdd, 0x50, 0x96, 0xc9, 0x98, 0x7e, 0xaf, 0x49, 0x69, 0x44, 0x38, 0x2a, 0x78, 0x4e, 0xa1,
	0x17, 0x79, 0xd7, 0xc3, 0xd8, 0x7c, 0xb3, 0x39, 0x80, 0xe5, 0x94, 0xd9, 0x06, 0x43, 0xe8, 0xe7,
	0xa4, 0x14, 0x5f, 0x36, 0xa4, 0xa6, 0xc4, 0x77, 0xd0, 0xd3, 0x4a, 0xf3, 0xbc, 0x0c, 0xfd, 0xc8,
	0xbb, 0x0e, 0x66, 0x27, 0x13, 0x23, 0x74, 0x2f, 0x72, 0x32, 0x70, 0x6c, 0x8f, 0xd9, 0x1c, 0x86,
	0xb7, 0x3c, 0x27, 0x55, 0xf2, 0x84, 0x90, 0xc1, 0x48, 0x56, 0x4b, 0x5e, 0x88, 0xbf, 0x5c, 0x0b,
	0x59, 0xd8, 0x47, 0xf7, 0x30, 0xbc, 0x02, 0x48, 0x64, 0x96, 0x51, 0x62, 0x18, 0xbe, 0x61, 0x38,
	0x08, 0xbb, 0x82, 0x41, 0x4c, 0x4a, 0xae, 0xab, 0x84, 0x6a, 0x07, 0x25, 0xd7, 0xab, 0xd0, 0x8b,
	0xba, 0xb5, 0x83, 0xfa, 0x9b, 0xfd, 0xf7, 0x20, 0xb8, 0x17, 0x19, 0x35, 0x2e, 0x3f, 0xc2, 0xb0,
	0x68, 0x1a, 0x30, 0x82, 0xc1, 0x0c, 0x27, 0x4d, 0x5a, 0x6d, 0x6b, 0xf1, 0x8e, 0x84, 0x1f, 0x60,
	0x50, 0x59, 0x05, 0xeb, 0xee, 0xac, 0xbd, 0xd0, 0x48, 0xc7, 0x2d, 0x05, 0x5f, 0x42, 0x2f, 0x27,
	0x5d, 0x89, 0x24, 0xec, 0x9a, 0x66, 0x6d, 0x85, 0x17, 0xf0, 0x4c, 0x14, 0x29, 0xfd, 0x09, 0x8f,
	0x0c, 0xbc, 0x2d, 0x58, 0x01, 0xa3, 0xb9, 0x6b, 0xf7, 0x39, 0xf8, 0x22, 0x35, 0x7d, 0x75, 0x63,
	0x5f, 0xa4, 0xed, 0x50, 0xfc, 0xdd, 0x50, 0x30, 0x82, 0x20, 0x25, 0x95, 0x54, 0xa2, 0x34, 0x99,
	0x6c, 0x65, 0x5c, 0xa8, 0x1e, 0x54, 0x52, 0x11, 0xd7, 0x94, 0x5a, 0xb5, 0xa6, 0x64, 0x97, 0xf0,
	0xca, 0xd5, 0xfb, 0x29, 0x94, 0xb6, 0xc9, 0xb0, 0x39, 0x9c, 0x3e, 0x3e, 0xc2, 0xaf, 0x70, 0xec,
	0x4e, 0x43, 0x99, 0x68, 0x83, 0xd9, 0x8b, 0x36, 0x00, 0xf7, 0x46, 0xbc, 0xcf, 0x65, 0xef, 0xe1,
	0x7c, 0xef, 0xf8, 0xe9, 0x3d, 0x9b, 0xfd, 0xf3, 0xa1, 0x7f, 0xbb, 0x7d, 0x12, 0xbf, 0xc0, 0xe0,
	0x8e, 0x6f, 0xcc, 0xda, 0xe1, 0x4e, 0xc8, 0x5d, 0xd5, 0xf1, 0xf9, 0x63, 0xb8, 0xcc, 0x36, 0xac,
	0x83, 0x9f, 0x61, 0xf8, 0x9d, 0x74, 0xb2, 0xaa, 0xe7, 0x8d, 0x17, 0x2d, 0xc7, 0x19, 0xff, 0xf8,
	0x74, 0xb7, 0x98, 0x77, 0x54, 0x09, 0x52, 0xac, 0x83, 0x31, 0x9c, 0xd5, 0x66, 0xdd, 0x5e, 0x15,
	0x46, 0x07, 0x2d, 0x3a, 0x79, 0x8d, 0x2f, 0x9f, 0x64, 0xb0, 0x0e, 0xde, 0xc0, 0xc9, 0x0f, 0xda,
	0x7b, 0x12, 0x5f, 0x1f, 0x0e, 0xcd, 0xbe, 0x76, 0x38, 0x52, 0xd6, 0xf9, 0xf6, 0xf6, 0xd7, 0x9b,
	0xa5, 0xd0, 0xab, 0xf5, 0x62, 0x92, 0xc8, 0x7c, 0x4a, 0xaa, 0x20, 0x3d, 0x35, 0x3f, 0xf0, 0x74,
	0x29, 0xa7, 0xf6, 0xce, 0xa2, 0x67, 0x90, 0x4f, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x31,
	0xa8, 0x9c, 0xf8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetbeamClient is the client API for Netbeam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetbeamClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Requests a tile from the netbeam core for a specific metric
	FetchTile(ctx context.Context, in *TileRequest, opts ...grpc.CallOption) (*pond.TimeSeries, error)
	// Request the list of Organizations registered with netbeam
	ListOrganizations(ctx context.Context, in *OrganizationListRequest, opts ...grpc.CallOption) (*OrganizationList, error)
	// Get a specific Organization by supplying it's short name
	GetOrganization(ctx context.Context, in *OrganizationRequest, opts ...grpc.CallOption) (*Organization, error)
}

type netbeamClient struct {
	cc *grpc.ClientConn
}

func NewNetbeamClient(cc *grpc.ClientConn) NetbeamClient {
	return &netbeamClient{cc}
}

func (c *netbeamClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/netbeam.Netbeam/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netbeamClient) FetchTile(ctx context.Context, in *TileRequest, opts ...grpc.CallOption) (*pond.TimeSeries, error) {
	out := new(pond.TimeSeries)
	err := c.cc.Invoke(ctx, "/netbeam.Netbeam/FetchTile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netbeamClient) ListOrganizations(ctx context.Context, in *OrganizationListRequest, opts ...grpc.CallOption) (*OrganizationList, error) {
	out := new(OrganizationList)
	err := c.cc.Invoke(ctx, "/netbeam.Netbeam/ListOrganizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netbeamClient) GetOrganization(ctx context.Context, in *OrganizationRequest, opts ...grpc.CallOption) (*Organization, error) {
	out := new(Organization)
	err := c.cc.Invoke(ctx, "/netbeam.Netbeam/GetOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetbeamServer is the server API for Netbeam service.
type NetbeamServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Requests a tile from the netbeam core for a specific metric
	FetchTile(context.Context, *TileRequest) (*pond.TimeSeries, error)
	// Request the list of Organizations registered with netbeam
	ListOrganizations(context.Context, *OrganizationListRequest) (*OrganizationList, error)
	// Get a specific Organization by supplying it's short name
	GetOrganization(context.Context, *OrganizationRequest) (*Organization, error)
}

// UnimplementedNetbeamServer can be embedded to have forward compatible implementations.
type UnimplementedNetbeamServer struct {
}

func (*UnimplementedNetbeamServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedNetbeamServer) FetchTile(ctx context.Context, req *TileRequest) (*pond.TimeSeries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTile not implemented")
}
func (*UnimplementedNetbeamServer) ListOrganizations(ctx context.Context, req *OrganizationListRequest) (*OrganizationList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrganizations not implemented")
}
func (*UnimplementedNetbeamServer) GetOrganization(ctx context.Context, req *OrganizationRequest) (*Organization, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganization not implemented")
}

func RegisterNetbeamServer(s *grpc.Server, srv NetbeamServer) {
	s.RegisterService(&_Netbeam_serviceDesc, srv)
}

func _Netbeam_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetbeamServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netbeam.Netbeam/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetbeamServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netbeam_FetchTile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetbeamServer).FetchTile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netbeam.Netbeam/FetchTile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetbeamServer).FetchTile(ctx, req.(*TileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netbeam_ListOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetbeamServer).ListOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netbeam.Netbeam/ListOrganizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetbeamServer).ListOrganizations(ctx, req.(*OrganizationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Netbeam_GetOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetbeamServer).GetOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netbeam.Netbeam/GetOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetbeamServer).GetOrganization(ctx, req.(*OrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Netbeam_serviceDesc = grpc.ServiceDesc{
	ServiceName: "netbeam.Netbeam",
	HandlerType: (*NetbeamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Netbeam_SayHello_Handler,
		},
		{
			MethodName: "FetchTile",
			Handler:    _Netbeam_FetchTile_Handler,
		},
		{
			MethodName: "ListOrganizations",
			Handler:    _Netbeam_ListOrganizations_Handler,
		},
		{
			MethodName: "GetOrganization",
			Handler:    _Netbeam_GetOrganization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netbeam.proto",
}
